config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    resources :slots
  end
  resources :slots_users, only: [:create, :destroy]
  get 'contact-us', to: 'home#contact'
  get 'about-us', to: 'home#about'
  get 'admin', to: 'home#admin'
  put 'give_admin/:id', to: 'home#give_admin', as: 'give_admin'
  put 'remove_admin/:id', to: 'home#remove_admin', as: 'remove_admin'
  get 'user/:id', to: 'home#user', as: 'user'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :slots, dependent: :destroy
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :event
  has_many :slots_users, dependent: :destroy
  has_many :users, through: :slots_users
end

app/models/slots_user.rb
class SlotsUser < ApplicationRecord
  belongs_to :user
  belongs_to :slot
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :slots_users
  has_many :slots, through: :slots_users
  validates :first_name, presence: true
  validates :last_name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :admin_check, only: [:new, :create, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save
    redirect_to @event, notice: 'Event created successfully.'
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id]).destroy
    redirect_to events_path, notice: 'Event deleted successfully.'
  end

  def admin_check
    redirect_to events_path, alert: 'Access denied' unless current_user.role == 1
  end

  private

  def event_params
    params.require(:event).permit(:event_name, :event_date)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :admin_check, only: [:admin, :give_admin, :remove_admin]
  before_action :authenticate_user!, only: [:user]

  def index
  end
  def contact
  end

  def admin
    @users = User.all
  end

  def give_admin
    @user = User.find(params[:id])
    @user.role = 1
    @user.save
    redirect_to events_path, notice: 'Admin added successfully.'
  end

  def user
    #show all the users bookings that they have made
    @user = User.find(params[:id])
    @slots = @user.slots
    @user_slot = SlotsUser.find_by(slot_id: params[:id], user_id: current_user.id)
  end

  def remove_admin
    @user = User.find(params[:id])
    @user.role = 0
    @user.save
    redirect_to events_path, notice: 'Admin removed successfully.'
  end

  def admin_check
    redirect_to events_path, alert: 'Access denied' unless current_user.role == 1
  end

end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :admin_check, only: [:new, :create]
  before_action :find_event, only: [:new, :create, :show]
  before_action :authenticate_user!, only: [:new, :create, :show]
  before_action :find_slotuser, only: [:show]

  def new
  end

  def create
    @slot = @event.slots.create(slot_params)
    redirect_to event_path(@event)
  end

  def show
    @user_slot = SlotsUser.find_by(slot_id: params[:id], user_id: current_user.id)
    @slot = Slot.find(params[:id])
  end

  def destroy
    @slot = Slot.find(params[:id]).destroy
    redirect_to events_path
  end

  def find_event
    @event = Event.find(params[:event_id])
  end

  def find_slotuser
    @user_slot = SlotsUser.find_by(slot_id: params[:id], user_id: current_user.id)
  end

  def admin_check
    redirect_to events_path, alert: 'Access denied' unless current_user.role == 1
  end

  private

  def slot_params
    params.require(:slot).permit(:slot_name, :slot_time)
  end


end

app/controllers/slots_users_controller.rb
class SlotsUsersController < ApplicationController
  before_action :authenticate_user!

  def create
    user = current_user
    slot = Slot.find(params[:slot_id])
    user.slots << slot
    redirect_to events_path, notice: 'Slot assigned to user successfully.'
  end

  def destroy
    @user_slot = SlotsUser.find(params[:id]).destroy
    redirect_to events_path, notice: 'Slot removed from user successfully.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/slots_users_helper.rb
module SlotsUsersHelper
end

app/views/events/index.html.slim
.d-flex.w-75.text-center.mx-auto
  h1 All Events
  - if user_signed_in?
    - if current_user.role == 1
      .ms-auto
        = link_to 'New Event', new_event_path, class: 'btn btn-success'
- @events.each do |event|
  .d-flex.justify-content-center
    .card.mt-4.shadow.w-75.d-flex.justify-center
      .card-body
        = link_to event_path(event), style: 'color: #333; text-decoration: none;' do
            .d-flex.w-100.justify-content-between
              h2 = event.event_name

              small #{event.event_date}
            p Sessions: #{event.slots.count}

app/views/events/new.html.slim
= form_for @event do |f|
  .field
    = f.label :event_name
    = f.text_field :event_name, required: true

  .field
    = f.label :event_date
    = f.date_field :event_date, required: true

  .actions
    = f.submit 'Create Event'

app/views/events/show.html.slim
.event.w-75.mx-auto
  .d-flex
    h2 = @event.event_name
    - if user_signed_in?
      - if current_user.role == 1
        .ms-auto
          = link_to "Delete", event_path(@event), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger'
  p Event Date: #{@event.event_date}


- if @event.slots.any?
  .d-flex.w-75.mx-auto.mt-5
    h2 Sessions
    .ms-auto
      = link_to 'New', new_event_slot_path(@event), class: 'btn btn-success'
  - @event.slots.each do |session|
    .d-flex.justify-content-center
        .card.mt-4.shadow.w-75.d-flex.justify-center
          .card-body
            = link_to event_slot_path(@event, session), style: 'color: #333; text-decoration: none;' do

              .d-flex.w-100.justify-content-between
                h2 = session.slot_name
                small #{session.slot_time}
              p Sessions:
- else
  .d-flex.w-75.mx-auto.mt-5
    h2 Sessions
    .ms-auto
      = link_to 'Create Sessions', new_event_slot_path(@event), class: 'btn btn-success'

app/views/home/about.html.slim
    .container
      .row
        .col-md-8.offset-md-2
          h2.text-center Welcome to Braintree BMX Club
          p.text-center
            | Braintree BMX Club is a vibrant community dedicated to the thrilling sport of BMX racing. Located in the heart of Braintree, we offer coaching sessions and organize exciting races for riders of all skill levels.
          p.text-center
            | Whether you're a seasoned pro or a beginner eager to learn, our experienced coaches are here to help you hone your BMX skills and enjoy the adrenaline rush of racing.
          p.text-center
            | Join us and be part of a supportive BMX community where riders come together to share their passion for the sport.
          h3.text-center Our Offerings
          ul.list-unstyled.text-center
            li
              | Professional BMX coaching sessions for all ages
            li
              | Thrilling BMX races and competitions
            li
              | Community events and social gatherings
          h3.text-center Join Us Today
          p.text-center
            | Ready to embark on an exhilarating BMX journey with us? Join Braintree BMX Club today and experience the excitement of BMX racing like never before.
          p.text-center
            | Contact us for more information or visit us at our next event!

app/views/home/admin.html.slim
h1.w-75.mx-auto Users 

- if user_signed_in?
  - if current_user.role == 1
    .mx-auto.w-75
      table.table.table-bordered.table-hover.
        thead
          tr
            th Email
            th Admin
            th Actions
        tbody
          - @users.each do |user|
            tr
              td = user.email
              td = "#{user.role == 1 ? 'Yes' : 'No'}"
              td.d-flex.justify-content-center
                = button_to "Give Admin", give_admin_path(user), method: :put, data: { confirm: "Are you sure you want to give admin rights?" }, class: "btn btn-success me-4", style: 'color: #333; text-decoration: none;', remote: true
                = button_to "Remove Admin", remove_admin_path(user), method: :put, data: { confirm: "Are you sure you want to remove admin rights?" }, class: "btn btn-danger", style: 'color: #333; text-decoration: none;', remote: true




                  

app/views/home/contact.html.slim
.w-75.mx-auto
  h1 Contact Us
  p Welcome to the heart of BMX enthusiasm in Braintree, England! 
  | The Braintree BMX Club is a thriving community of riders, passionate about the exhilarating world of Bicycle Motocross. Nestled in the vibrant sports scene of Braintree, our club serves as a hub for riders of all ages and skill levels. Established with the mission to foster a love for BMX, we provide a dynamic space where riders can hone their skills, engage in friendly competition, and form lasting connections with fellow enthusiasts. Our dedicated team is committed to promoting the sport, organizing exciting events, and creating an inclusive atmosphere that encourages both newcomers and seasoned riders. Join us in the pursuit of adrenaline, sportsmanship, and the thrill of the track at the Braintree BMX Club!

app/views/home/index.html.slim
.w-75.mx-auto
  h1.text-center Welcome to the Braintree BMX Club Booking System 
  .d-flex.justify-content-center
    = image_tag('Home.jpg', alt: 'Your Alt Text', class: 'img-fluid mt-4')

app/views/home/user.html.slim
.w-75.mx-auto
  h1 My Account 
  h3 My Details
  p First Name: #{current_user.first_name}
  p Last Name: #{current_user.last_name}
  p Email: #{current_user.email}
  p Admin: #{current_user.role == 1 ? 'Yes' : 'No'}
  h3 My Bookings 
  - if current_user.slots.any?
    table.table.table-striped
      thead
        tr
          th Event
          th Session
          th Date
          th Time
          th Cancel Booking
      tbody
        - current_user.slots.each do |slot|
          tr
            td #{slot.event.event_name}
            td #{slot.slot_name}
            td #{slot.event.event_date}
            td #{slot.slot_time}
            td.ms-auto
              = button_to "Cancel Booking", slots_user_path(slot.slots_users.find_by(user: current_user)), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: 'btn btn-danger'
  - else
    p You have no bookings yet.


  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BmxBooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag 'icon.png' %>

  </head>
  <body>
  <%= render "components/nav"%> 

  <p class="notice"><%= notice %></p> 
  <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/slots/new.html.slim
h1 New Session for 
= @event.event_name

= form_with model: [ @event, @event.slots.build ] do |f|
  .field
    = f.label :slot_name
    = f.text_field :slot_name, required: true

  .field
    = f.label :slot_time
    = f.time_field :slot_time, required: true
  = f.submit 'Create Session'

app/views/slots/show.html.slim
h1 Session Details

.slot
  h2 = @slot.slot_name
  p Event time: #{@slot.slot_time}
= link_to 'Back to Events', events_path(@event)

- if @user_slot
  = button_to "Cancel Booking", slots_user_path(@user_slot), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: 'btn btn-danger'
- else
  = form_with url: slots_users_path, method: :post, local: true do |form|
    = form.hidden_field :slot_id, value: @slot.id
    = form.submit 'Book Session', class: 'btn btn-primary'

- if user_signed_in?
  - if current_user.role == 1
    = link_to "Destroy", event_slot_path(@slot), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }